/*
 * DinoConfig Java SDK - Generated Model
 * Generated by @dinoconfig/cli
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from DinoConfig schema.
 * 
 * Brand: Test
 * Config: Test3
 */
package org.example.models.test;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * Generated model for Test3 configuration.
 *
 * <p>This class represents the typed structure of the configuration.
 * All fields are immutable.
 */
public final class Test3 {
    /**
     * string - time_1
     */
    @JsonProperty("time_1")
    private final String time_1;

    /**
     * string - datetime_1
     */
    @JsonProperty("datetime_1")
    private final String datetime_1;

    /**
     * Default constructor for Jackson deserialization.
     */
    public Test3() {
        this.time_1 = null;
        this.datetime_1 = null;
    }

    /**
     * Creates a new Test3 instance.
     *
     * @param time_1 time_1 (string)
     * @param datetime_1 datetime_1 (string)
     */
    public Test3(String time_1, String datetime_1) {
        this.time_1 = time_1;
        this.datetime_1 = datetime_1;
    }

    /**
     * Returns time_1.
     *
     * @return time_1 (string)
     */
    public String getTime_1() {
        return time_1;
    }

    /**
     * Returns datetime_1.
     *
     * @return datetime_1 (string)
     */
    public String getDatetime_1() {
        return datetime_1;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Test3 that = (Test3) o;
        return Objects.equals(time_1, that.time_1)
                && Objects.equals(datetime_1, that.datetime_1);
    }

    @Override
    public int hashCode() {
        return Objects.hash(time_1, datetime_1);
    }

    @Override
    public String toString() {
        return "Test3{" +
                "time_1=" + time_1 +
                ", datetime_1=" + datetime_1 +
                '}';
    }
}
